version: "3.9" # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "8000:8000"
    links:
      - redis
  redis:
    image: redis
    command: redis-server --save 60 1 --loglevel warning
volumes:
  logvolume01: {}
